CREATE TABLE IF NOT EXISTS tableSales
(
    ID  SERIAL PRIMARY KEY,
    RC_ID INTEGER,
    AR_ID INTEGER,
    WH_ID INTEGER,
    SALES DECIMAL
);
CREATE TABLE IF NOT EXISTS tableValue
(
    ID  SERIAL PRIMARY KEY,
    RC_ID   INTEGER,
    AR_ID   INTEGER,
    WH_ID   INTEGER,
    TYPE_ID INTEGER,
    QNTY    DECIMAL,
    PERC    DECIMAL
);
CREATE TABLE IF NOT EXISTS tableType
(
    ID  SERIAL PRIMARY KEY,
    AR_ID   INTEGER,
    TYPE_ID INTEGER

);

--DROP TABLE IF EXISTS tableSales;
--DROP TABLE IF EXISTS tableValue;
--DROP TABLE IF EXISTS tableType;
